@startuml Package **cloudapps.mastermind.models**

package "cloudapps.mastermind.models" {

  class Game {
    -Board board
    +Game()
    +reset(): void
    +getSecretCombination(): SecretCombination
    +addProposedCombination(ProposedCombination):void
    +getAttempts(): int
    +getProposedCombination(int): ProposedCombination
    +isWinner(): boolean
    +isLooser(): boolean
    +getResult(int): Result
  }
  
  class Board {
    -{static} final int MAX_ATTEMPS
    -SecretCombination secretCombination
    -ProposedCombination[] proposedCombination
    -Result[] results
    +Board()
    +reset():void
    +addProposedCombination(ProposedCombination):void
    +isWinner(): boolean
    +isLooser(): boolean
    +{static}maxAttempts(): int
    +getAttempts(): int
    +getSecretCombination(): SecretCombination
    +getProposedCombination(int): ProposedCombination
    +getResult(int): Result 
  }
  
  abstract class Combination {
    -{static} final int LENGTH
    #List<Color> colors
    #Combination()
    +{static}length(): int 
    +getColors(): List<Color>
  }
  
  class SecretCombination {
    +SecretCombination()
    -generate(): void
    +getResult(ProposedCombination): Result
    +getColorAt(int): Color
  }
  
  class ProposedCombination {
    +contains(Color): boolean
    +contains(Color, int): boolean
  }
  
  enum Color {
    RED
    BLUE
    YELLOW
    GREEN
    ORANGE
    PURPLE
    +{static} length(): int
  }
  
  enum Error {
    DUPLICATED,
	  WRONG_CHARACTERS,
	  WRONG_LENGTH,
	  NULL_ERROR
    +isNull(): boolean
  }
  
  class Result {
    -int blacks
    -int whites
    +Result(int, int)
    +isWinner(): boolean
    +getBlacks(): int
    +getWhites(): int
  }
  
  Game *--> Board
  Board *--> SecretCombination
  Board *--> ProposedCombination
  Color *-->  java.util.List
  Board *--> Result
  Game *--> Result
  
  Combination <|-- SecretCombination
  Combination <|-- ProposedCombination
  Combination *--> Color
  
  SecretCombination ..> Result
  SecretCombination ..> ProposedCombination
  
  ProposedCombination ..> Error
  ProposedCombination ..> Color
  
}

package "java.util" {
  
  class List {}


@enduml
